# LIBS
library(testthat)

# RUNNING
cleanup()
context('Testing \'connection-tools\'')
test_that('restez_ready() works', {
  expect_false(restez_ready())
  setup()
  restez_connect()
  on.exit(cleanup())
  expect_false(restez_ready())
  demo_db_create()
  restez_connect()
  expect_true(restez_ready())
})
test_that('restez_connect() works', {
  expect_error(restez_connect())
  setup()
  on.exit(cleanup())
  restez_connect()
  expect_true(is(connection_get(), 'duckdb_connection'))
})
test_that('restez_connect() works in read-only mode', {
  expect_error(restez_connect())
  setup()
  on.exit(cleanup())
  restez_connect(read_only = TRUE)
  expect_true(is(connection_get(), 'duckdb_connection'))
})
test_that('restez_disconnect() works', {
  expect_null(restez_disconnect())
  setup()
  on.exit(cleanup())
  restez_connect()
  expect_true(is(connection_get(), 'duckdb_connection'))
  restez_disconnect()
  expect_error(connection_get())
})
test_that('connected() works', {
  expect_false(connected())
  setup()
  on.exit(cleanup())
  expect_false(connected())
  restez_connect()
  expect_true(connected())
})
test_that('has_data() works', {
  expect_false(has_data())
  setup()
  restez_connect()
  on.exit(cleanup())
  expect_false(has_data())
  demo_db_create(n = 10)
  restez_connect()
  expect_true(has_data())
})
test_that('connection_get() works', {
  setup()
  restez_connect()
  on.exit(cleanup())
  expect_true(is(connection_get(), 'duckdb_connection'))
  cleanup()
  expect_error(connection_get())
})
cleanup()
